print("")
print("Cryptography")
print("The study of secret writing")
input("press enter to continue")
print("")
print("There are two main categories of classical cryptography")
input("press enter to continue")
print("")
print("Substitution")
print("individual letters or groups of letters are replaced by other letters, numbers, or special characters")
input("press enter to continue")
print("")
print("Transpositional")
print("the position of the letters is changed")
input("press enter to end program")
print("")
